import type { Handoff, AdapterOutput, AdapterOptions } from '../types.js';
import { allocateBudget } from '../compress/budgetAllocator.js';
import { compress } from '../compress/compress.js';
import { estimateTokens } from '../utils.js';

export function toGemini(handoff: Handoff, options: AdapterOptions = {}): AdapterOutput {
  const budgets = allocateBudget(handoff, 'gemini', options.tokenBudget);
  const compressed = compress(handoff, budgets);

  const lines: string[] = [];

  lines.push(`## CONTEXT (resuming from ${handoff.sources[0]?.tool || 'AI session'})`);
  lines.push(`*Generated by Smart Handoff — ${handoff.createdAt}*`);
  lines.push('');

  // Goal
  lines.push('### Goal');
  for (const goal of compressed.goals) {
    lines.push(`**${goal.title}**`);
    lines.push(goal.description);
  }
  lines.push('');

  // Goal progression (how the session's focus evolved)
  if (compressed.goalProgression && compressed.goalProgression.length > 1) {
    lines.push('### How the goal evolved');
    for (const g of compressed.goalProgression) {
      lines.push(`- ${g}`);
    }
    lines.push('');
  }

  // Active PR
  if (handoff.prLinks && handoff.prLinks.length > 0) {
    lines.push('### Active PR');
    for (const link of handoff.prLinks) {
      lines.push(link);
    }
    lines.push('');
  }

  // Session history (prior compact summaries — what happened before context reset)
  if (compressed.sessionSegments && compressed.sessionSegments.length > 0) {
    lines.push('### Session history (prior context windows)');
    for (const seg of compressed.sessionSegments) {
      const branch = seg.gitBranch ? ` [${seg.gitBranch}]` : '';
      lines.push(`**${seg.timestamp.slice(0, 10)}${branch}**`);
      lines.push(seg.summary);
      lines.push('');
    }
  }

  // Files changed
  if (compressed.filesChanged.length > 0) {
    lines.push('### Files changed');
    for (const file of compressed.filesChanged) {
      lines.push(`**${file.path}** (${file.status}, ${file.importance})`);
      if (file.summary) lines.push(`Summary: ${file.summary}`);
      if (file.diff && budgets.filesChanged > 3000) {
        lines.push('```diff');
        lines.push(file.diff.slice(0, 2000));
        lines.push('```');
      }
    }
    lines.push('');
  }

  // Blocker
  if (compressed.blockers.length > 0) {
    lines.push('### Open blocker');
    const b = compressed.blockers[0]!;
    lines.push(b.description);
    if (b.errorMessage) lines.push(`Error: \`${b.errorMessage}\``);
    if (b.errorLocation) lines.push(`Location: ${b.errorLocation}`);
    lines.push('');
  }

  // Decisions
  if (compressed.decisions.length > 0) {
    lines.push('### Decisions made (do not re-suggest)');
    for (const d of compressed.decisions) {
      lines.push(`- ${d.summary}`);
    }
    lines.push('');
  }

  // Next step
  if (compressed.nextSteps.length > 0) {
    lines.push('### Next step');
    lines.push(compressed.nextSteps[0]!.specificAction || compressed.nextSteps[0]!.description);
    lines.push('');
  }

  // Stack
  if (compressed.context.stack.length > 0) {
    lines.push('### Stack');
    lines.push(compressed.context.stack.join(', '));
    if (compressed.context.testCommand) {
      lines.push(`Test: \`${compressed.context.testCommand}\``);
    }
    lines.push('');
  }

  // CLAUDE.md (Gemini budget allows it)
  if (compressed.context.claudeMdContent && budgets.claudeMd > 0) {
    lines.push('### Project instructions (CLAUDE.md)');
    lines.push(compressed.context.claudeMdContent);
    lines.push('');
  }

  const text = lines.join('\n');
  const geminiMd = generateGeminiMd(handoff);

  return {
    text,
    deliveryMethod: 'pipe',
    targetTool: 'gemini',
    tokenCount: estimateTokens(text),
    filesToWrite: [{
      path: 'GEMINI.md',
      content: geminiMd,
      isTemporary: false,
    }],
    launchCommand: `gemini --skip-trust`,
  };
}

function generateGeminiMd(handoff: Handoff): string {
  const lines: string[] = ['# Project Context'];
  if (handoff.context.claudeMdContent) {
    lines.push(handoff.context.claudeMdContent);
  }
  if (handoff.context.stack.length > 0) {
    lines.push('\n# Stack');
    lines.push(handoff.context.stack.join('\n'));
  }
  return lines.join('\n');
}
